<a href="https://colab.research.google.com/github/dalematt/MLBlog/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

More specifically, we're going to cover:
introduction to tensors
gettinginformation from tensors
manipulating tensors
Numpy
tf.functions
using GPUs with tf



In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)


2.8.2


In [3]:
#create tensors with tf.constant()
scalar= tf.constant(7)  
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [8]:
#create a vector
vector=tf.constant([10,10])
vector
vector.ndim

1

In [12]:
matrix=tf.constant([[10,7],[7,10]])
matrix



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:

matrix.ndim


2

In [18]:
another_matrix=tf.constant([[10.,7.],
                            [1.,2.],
                            [8.,0.]],dtype=tf.float16)
another_matrix
another_matrix.ndim

2

In [21]:
tensor=tf.constant([[[1,2,3],[4,5,6]],[[19,11,12],[120,11,16]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 19,  11,  12],
        [120,  11,  16]]], dtype=int32)>

In [22]:
tensor.ndim

3